[workspace]

members = [
    "secure-conductor", "secure-conductor-broker",
]

[profile.dev]
codegen-units = 16
opt-level = 0
incremental = true
debug = true

[profile.release]
codegen-units = 1
strip = "symbols"
lto = "fat"
panic = "abort"
opt-level = 3
